### ISSUE TITLE
Weird Chars amongst lines of code

### ISSUE THREAD

**Issue by HawkeyeZAR** [VenimK/rustdesk_builder_windows#2]
In both files there are multiple ascii chars that breaks the code, below an example of one.  

`[System.Environment]::SetEnvironmentVariable(â€˜VCPKG_ROOTâ€™`

**Comment by HawkeyeZAR** [comment]
I copied the code directly from the screen, it seems only the downloaded files are affected with those weird chars.

**Comment by VenimK** [comment]
I' l check it this weekend
Greetingz

**Comment by VenimK** [comment]
> I copied the code directly from the screen, it seems only the downloaded files are affected with those weird chars.

this does not happên, when you do a 

git clone https://github.com/VenimK/rustdesk_builder_windows.git

Right ??

**Comment by HawkeyeZAR** [comment]
yes, happens with a git clone as well
![Untitled](https://github.com/user-attachments/assets/e92e7a55-27df-4ea4-a0b3-7bf2115e0020)

**Comment by VenimK** [comment]
Should be fixed now
Sorry for the delay

https://github.com/VenimK/rustdesk_builder_windows

**Comment by HawkeyeZAR** [comment]
Thanks, it is now working.

**Comment by VenimK** [comment]
Updated some stuff
You might try them
Build_custom

**Comment by HawkeyeZAR** [comment]
Nice job, I like the cleanup features of old files and cache.  I just added the below code to your custom script.
It basically packs everything into one executable.

```
mv ./flutter/build/windows/x64/runner/Release ./rustdesk
pushd ./libs/portable
pip install -r requirements.txt
Write-Host "Building new rustdesk exe, combining all files into one exe"
python ./generate.py -f ../../rustdesk/ -o . -e ../../rustdesk/rustdesk.exe
popd
Write-Host "Deleting old rustdesk exe and dll's"
Remove-Item -Path "rustdesk" -Force -ErrorAction SilentlyContinue
Write-Host "New Single EXE can be found here, BuildRustdesk\rustdesk\target\release"
```
